### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by johnmckellar**
Changes to time-rock units.

I also note that, in the ttl file, there are features without any spatial data, e.g., the Stanwell Basin (and the list of others down at the bottom of it), whereas the equivalent Styx Basin does. If there are units in this file without spatial info, then should I add other units that do not have any spatial info that are missing from the file (e.g. Kennedy & Macrossan Igneous Provinces/Associations and their subunits)?

### CODE REVIEW

**Comment by johnmckellar** [comment]
Hi Vance, 

This has been a learning experience that I hope is a positive one, taking the file from VS on my desktop back to here as a PR.

Fingers crossed that it has worked. I'll let you decide who else to assign, if I may. Let me know, as you will, if it has not worked out as hoped.

Cheers

**Review by KellyVance — CHANGES_REQUESTED** [review]
Changes are reasonable, but two minor file fixes required for approval.

line 673 needs to end in ; rather than ,
line 830 needs to end in , then delete blank line 831

**Comment by KellyVance** [comment]
@DavidCrosswellGSQ  can you please provide a technical check when you have a moment and comment on John's spatial question.

**Comment by johnmckellar** [comment]
Well spotted Vance!! I have looked at my home-desktop file in VS, and made the edits there, but I take it that you have already done this in same file that I uploaded. Can I then take this for granted, and pending David's response, we can then decide which way to then proceed.

If there are issues with adding a note (re querying the age in question), we can just skip it. As Bob Bultitude said, there are a lot of queries against a number of ages anyway.

**Comment by KellyVance** [comment]
@johnmckellar I havent changed the file here. I thought I'd let you change in your local version and upload back into this pull request. Best to keep as few copies floating around as possible. I'm sure id forget i'd saved it locally and then panic in 6 months wondering which is the correct file. 

For ages I was only looking for truly egregious errors. I'll leave the finer details in your far-more-capable hands.

**Comment by johnmckellar** [comment]
OK Vance. I have made the changes here. It becomes a little more complex for everyone when you have to take the the files out of GitHub to deal with!!

**Review by KellyVance — APPROVED** [review]
Approved!

**Comment by johnmckellar** [comment]
@KellyVance Vance, How and where do I introduce the command line: 'git checkout -b johnmckellar-patch-1 origin/johnmckellar-patch-1' please? See the above.

This has been approved, but only by you, for corrections to ages. I need to merge this file so that I can make further changes.

Cheers

**Comment by johnmckellar** [comment]
@katewd Hi Kate, As stated in our meeting this morning, there is some conflict preventing merging of my branch into the Master.

The instructions given are:

Checkout via command line

If you cannot merge a pull request automatically here, you have the option of checking it out via command line to resolve conflicts and perform a manual merge.

Step 1: From your project repository, bring in the changes and test.

git fetch origin
git checkout -b johnmckellar-patch-1 origin/johnmckellar-patch-1
git merge master

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff johnmckellar-patch-1
git push origin master

I have played around with this to no avail, yesterday and again this morning. Maybe the file is too large for GitHub?? If you want to view the file, you have to export it to Visual Studio (as, again, it is too large for GitHub). Also, the file has been reviewed by only a single reviewer.

Please see if you can determine what the conflict is. It looked good to Vance. 

Many thanks.

**Pull request merged**
